const K='kfh_products',O='kfh_orders',C='kfh_colors',D='kfh_designs';
const seed=[{id:'p1',name:'Classic Print T-Shirt',category:'Print T-Shirt',price:2490,colors:['Black','White'],sizes:['S','M','L','XL'],image:'',description:'Custom printed T-shirt. Choose your colour and size.'},{id:'p2',name:'Elegant Ladies Dress',category:'Dresses',price:4990,colors:['Black','Pink'],sizes:['S','M','L','XL'],image:'',description:'Elegant ladies fashion dress.'},{id:'p3',name:'Couple Matching Set',category:'Couple / Matching',price:6990,colors:['Black','White'],sizes:['M','L','XL'],image:'',description:'Matching outfit for special moments.'}];
function get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}function set(k,v){localStorage.setItem(k,JSON.stringify(v))}if(!localStorage.getItem(K))set(K,seed);if(!localStorage.getItem(C))set(C,[{n:'Black',h:'#111'},{n:'White',h:'#f5f5f5'},{n:'Red',h:'#e33'},{n:'Blue',h:'#2563eb'},{n:'Green',h:'#16a34a'},{n:'Pink',h:'#ec4899'}]);if(!localStorage.getItem(O))set(O,[]);if(!localStorage.getItem(D))set(D,[]);function money(x){return 'Rs. '+Number(x||0).toLocaleString('en-LK')}
function card(p){return `<article class="card"><img src="${p.image||'assets/logo.png'}"><div class="card-body"><span class="tag">${p.category}</span><h3>${p.name}</h3><div class="price">${money(p.price)}</div><p class="muted">${p.description||''}</p><div class="actions"><a class="gold" href="product.html?id=${p.id}">View & Order</a></div></div></article>`}
function render(id,cat){let e=document.getElementById(id);if(!e)return;let a=get(K,[]).filter(p=>!cat||p.category===cat);e.innerHTML=a.length?a.map(card).join(''):'<div class="empty">Products ඔයා Admin Panel එකෙන් add කළාම මෙතන පෙන්වයි.</div>'}
function product(){let id=new URLSearchParams(location.search).get('id');return get(K,[]).find(p=>p.id===id)}
function initProduct(){let e=document.getElementById('product');if(!e)return;let p=product();if(!p){e.innerHTML='<div class="empty">Product not found.</div>';return}let colors=p.colors||get(C,[]).map(x=>x.n);e.innerHTML=`<div class="two"><div class="panel"><img class="checkout-img" src="${p.image||'assets/logo.png'}"></div><div class="panel"><span class="tag">${p.category}</span><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="muted">${p.description||''}</p><h3>🎨 Color</h3><div class="swatches">${colors.map((c,i)=>`<button class="swatch ${i===0?'active':''}" onclick="pick(this)">${c}</button>`).join('')}</div><h3>📏 Size</h3><div class="swatches">${(p.sizes||['S','M','L','XL']).map((s,i)=>`<button class="swatch ${i===0?'active':''}" onclick="pick(this)">${s}</button>`).join('')}</div><h3>🔢 Quantity</h3><input id="qty" type="number" min="1" value="1" style="width:90px;padding:10px;background:#0b0b0b;color:#fff;border:1px solid #333;border-radius:9px"><div class="actions" style="margin-top:18px"><a class="gold" href="checkout.html?id=${p.id}">Order Now</a></div></div></div>`}function pick(b){b.parentElement.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active')}
function initCheckout(){let e=document.getElementById('checkout');if(!e)return;let p=product();if(!p){e.innerHTML='<div class="empty">Product එකක් select කරන්න.</div>';return}e.innerHTML=`<div class="two"><div class="panel"><img class="checkout-img" src="${p.image||'assets/logo.png'}"><h2>${p.name}</h2><div class="price">${money(p.price)}</div></div><div class="panel"><h2>📦 Delivery Details</h2><div class="form"><div class="field"><label>Full Name</label><input id="nm"></div><div class="field"><label>Phone Number</label><input id="ph"></div><div class="field"><label>Address</label><textarea id="ad"></textarea></div><div class="field"><label>City</label><input id="ci"></div><div class="field"><label>District</label><input id="di"></div><div class="field"><label>Postal Code</label><input id="po"></div><div class="notice"><b>💳 Payment</b><p>Bank Deposit / Online Bank Transfer</p><p>Commercial Bank<br>Account Holder: T.A. Nimali Priyanka<br>Account: 8027338007<br>Kuliyapitiya Branch</p><p class="muted">Production version එකේ secure payment gateway එක connect කළ පසු online payment verification automatic කරන්න පුළුවන්.</p></div><button class="gold" onclick="placeOrder('${p.id}')">Place Order</button></div></div></div>`}
function placeOrder(id){let p=get(K,[]).find(x=>x.id===id);let nm=document.getElementById('nm').value,ph=document.getElementById('ph').value,ad=document.getElementById('ad').value,ci=document.getElementById('ci').value;if(!nm||!ph||!ad||!ci){alert('Delivery details සම්පූර්ණ කරන්න.');return}let a=get(O,[]);a.unshift({id:'ORD'+Date.now().toString().slice(-7),product:p.name,total:p.price,customer:nm,phone:ph,address:ad,city:ci,payment:'Pending',status:'Pending',date:new Date().toLocaleString()});set(O,a);alert('Order එක save කළා. Payment verify කිරීම Admin Panel එකෙන් කරන්න.');location.href='account.html'}
function initAccount(){let e=document.getElementById('orders');if(!e)return;let a=get(O,[]);e.innerHTML=a.length?a.map(o=>`<p><b>${o.id}</b> — ${o.product} — ${money(o.total)} — <span class="tag">${o.payment}</span></p>`).join(''):'<div class="empty">Orders නැහැ.</div>'}
function initAdmin(){let p=get(K,[]),o=get(O,[]);document.getElementById('sp')&&(sp.textContent=p.length);document.getElementById('so')&&(so.textContent=o.length);document.getElementById('spa')&&(spa.textContent=o.filter(x=>x.payment==='Paid').length);let tb=document.getElementById('pt');if(tb)tb.innerHTML=p.map(x=>`<tr><td>${x.name}</td><td>${x.category}</td><td>${money(x.price)}</td><td><button class="btn" onclick="delP('${x.id}')">Delete</button></td></tr>`).join('');let ot=document.getElementById('ot');if(ot)ot.innerHTML=o.map(x=>`<tr><td>${x.id}</td><td>${x.product}</td><td>${x.customer}</td><td>${money(x.total)}</td><td><select onchange="pay('${x.id}',this.value)"><option ${x.payment==='Pending'?'selected':''}>Pending</option><option ${x.payment==='Paid'?'selected':''}>Paid</option></select></td><td>${x.status}</td></tr>`).join('')||'<tr><td colspan="6">Orders නැහැ.</td></tr>';let cl=document.getElementById('cl');if(cl)cl.innerHTML=get(C,[]).map(x=>`<span class="swatch"><span style="display:inline-block;width:13px;height:13px;border-radius:50%;background:${x.h};border:1px solid #777"></span> ${x.n}</span>`).join('')}
function delP(id){set(K,get(K,[]).filter(x=>x.id!==id));location.reload()}function pay(id,v){let a=get(O,[]);let x=a.find(o=>o.id===id);if(x)x.payment=v;set(O,a);location.reload()}
function addP(){let f=document.getElementById('pf');let p={id:'p'+Date.now(),name:f.n.value,category:f.c.value,price:Number(f.p.value),colors:f.co.value.split(',').map(x=>x.trim()),sizes:f.s.value.split(',').map(x=>x.trim()),image:f.i.value,description:f.d.value};if(!p.name||!p.price){alert('Name + Price දෙන්න');return}let a=get(K,[]);a.push(p);set(K,a);alert('Product added');location.reload()}
function addColor(){let n=document.getElementById('cn').value,h=document.getElementById('ch').value;if(!n)return;let a=get(C,[]);a.push({n,h});set(C,a);location.reload()}
function initDesigns(){let e=document.getElementById('designs');if(!e)return;let a=get(D,[]);e.innerHTML=a.length?a.map((x,i)=>`<article class="card"><img src="${x.image}"><div class="card-body"><a class="gold" href="print-tshirt.html">Order this design</a></div></article>`).join(''):'<div class="empty">Admin Panel එකෙන් designs add කළාම මෙතන පෙන්වයි.</div>'}
function addDesign(){let x=document.getElementById('diimg').value;if(!x)return;let a=get(D,[]);a.push({image:x});set(D,a);location.reload()}
document.addEventListener('DOMContentLoaded',()=>{render('all');render('print','Print T-Shirt');render('dress','Dresses');render('girls','Girls');render('gents','Gents');render('couple','Couple / Matching');render('new');render('offers');initProduct();initCheckout();initAccount();initAdmin();initDesigns()});
